### ISSUE TITLE
Bug on .remove API

### ISSUE THREAD

**Issue by davit-b** [oh-jinsu/typesafe-dynamo#2]
Doing 
```ts
const resp = await coach_table.remove(({ key }) => [
        key({
          userId: external_id ?? userId,
          coachId: coachId,
        }),
      ])

console.log(resp)
```

resp is logged out as undefined. 

I looked through AWS SDK v2 docs and have a feeling it should at least return something
https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/DynamoDB.html#deleteItem-property

<img width="772" alt="Screenshot 2023-07-14 at 10 35 38 AM" src="https://github.com/oh-jinsu/typesafe-dynamo/assets/12516060/0fbf29ab-785b-4932-b56b-980eb9eec425">

**Comment by oh-jinsu** [comment]
For the `delete` operation in `DocumentClient`, you can get a atrributes map which is the item before deletion if you put a `ReturnValues` parameter as `ALL_OLD`. Other things are just about async handlers and a table metadata like a comsumed capacity. Check out this reference: https://docs.aws.amazon.com/sdk-for-ruby/v2/api/Aws/DynamoDB/Types/DeleteItemOutput.html

I did not expose it as a result because in most cases I do not have to use or read them. Could you let me know specific usecases to get them? I'll consider to provide some options to expose them as a result.

Thank you.

**Comment by davit-b** [comment]
I don't need the ReturnValues.
I want the resp from the await to indicate an HTTP status if the delete was successful or not. Maybe a 500 in the case that the request failed due to some network error, or a 4xx in the case that the item selected for `delete` did not exist, and a 200 in the case that the operation succeeded.

**Comment by oh-jinsu** [comment]
Right so now it doesn't inform anything for any error results.

I can make operations including the `remove` function throw an `AWSError` if any error occurs. So that you can `catch` it.

**Comment by davit-b** [comment]
Perfect, thank you!
